[package]
name = "hapi"
version = "0.1.0"
authors = ["Will Springer <skirmisher@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.3.2"
libflate = "^0.1.26"
